### ISSUE TITLE
Сemetery of projects

### ISSUE THREAD

**Issue by SmartFinn** [PapirusDevelopmentTeam/ARCHIVE#1]
Не стоило на мой взгляд так делать. Лучше было бы закрыть issues и написать что этот проект уже не поддерживается, но оставить структуру и дать возможность пользоваться всем желающим. Может кто-то бы форкнул и занялся поддержкой.

Особенно жалко проект для KDE, я им хоть не пользуюсь, но он в актуальном состоянии, устанавливается и выглядит отлично на свежих дистрибутивах. Рано его вот так хоронить.

**Comment by varlesh** [comment]
Сейчас поясню почему я избавился от версии KDE.
Во-первых им мало кто пользуется, это можно было отследить по количеству запросов и лайков.
Во-вторых, я им давно уже не пользуюсь, вместо него теперь Arc будет
В-третьих оно отнимает кучу времени. Мне приходится рисовать иконки дважды, делать дважты коммиты.
В-четвертых, оно не удалено, а переммещено в архив, кто хочет, то восстановит структуру и всё запилит...
Я больше не поддерживаю данные проекты!

**Comment by varlesh** [comment]
Тема иконок теперь объединена для KDE и GTK. Структура каталогов немного изменилась, скрипты поправлены (я знаю, что там * есть, но это временно, так как для кед тема раньше называлась papirus и т.д.)

**Comment by SmartFinn** [comment]
Мотивация у меня вопросов не вызывает, просто дико видеть как open-source проекты так хоронят.

**Comment by varlesh** [comment]
Ну а что прикажете делать? Весь проект на мне держится по большому счету... а у меня не хватает времени всё это поддерживать :(
Подход был изначально не правильный, потому сейчас пожинаю плоды своей тупости.

**Comment by varlesh** [comment]
Поможете запилить скрипт для арка кде?

**Comment by varlesh** [comment]
Пути:
~/.local/share/aurorae/themes/{Arc,Arc-Dark,Arc-Transparent,Arc-Dark-Transparent}
~/.local/share/color-schemes/{Arc.colors,ArcDark.colors}
~/.local/share/konsole/{Arc.colorscheme,ArcDark.colorscheme}
~/.config/Kvantum/{ArcDark,ArcDarkTransparent}
~/.local/share/plasma/desktoptheme/Arc-Dark
~/.local/share/plasma/look-and-feel/com.github.varlesh.arc-dark
~/.local/share/wallpapers/{Arc,Arc-Dark}
~/.local/share/yakuake/kns_skins/{arc,arc-dark}

**Comment by SmartFinn** [comment]
Конечно!

**Comment by varlesh** [comment]
Огромное спасибо!!! На папку extra не обращайте внимания
